services:
  db:
    image: postgres:16
    attach: false
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: employee-db
    ports:
      - "5432:5432"
    volumes:
      - employeeDB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  employeeDB:
